### ISSUE TITLE
[Question] Azure pipelines status

### ISSUE THREAD

**Issue by eddynaka** [Azure/pipelines#20]
Hi,

when I use azure pipelines action, it triggers the pipeline but it does not wait for the pipeline to finish, so even if the build fails, the PR in GitHub does not get blocked.

Is it possible to do something like that?

Doing a direct integration with Azure Pipelines, it shows the status, but it does not block the PR from merge.

**Comment by m-akinc** [comment]
Did you find a workable solution? I also was hoping for something like this.

**Comment by eddynaka** [comment]
Hi @m-akinc ,

I didn't.
