### ISSUE TITLE
All Azure pipeline tests failed on pull request

### ISSUE THREAD

**Issue by Ashis26** [Azure/pipelines#39]
I am new to open source. I tried to contribute to issue #42124. I have to add an example of pandas.DataFrame.reorder_levels in frame.py script of pandas module [](https://github.com/pandas-dev/pandas/blob/master/pandas/core/frame.py#L6825-L6853) at the end. 
I have added the example which is shown here.
#------------------------------------------------------------------------- 
    
       pandas.DataFrame.reorder_levels
DataFrame.reorder_levels(order, axis=0)[source]
Rearrange index levels using input order. May not drop or duplicate levels.

Parameters
orderlist of int or list of str
List representing new level order. Reference level by number (position)
or by key (label).

axis{0 or ‘index’, 1 or ‘columns’}, default 0
Where to reorder levels.

Returns
DataFrame

    '''
# Example
# We create a dataframe with multiple index columns
import pandas as pd
data= pd.DataFrame({'Index1':[1,2,3,4,5],'Index2':['a','b','c','d','e'],'col1':['one','two','three','one','two']})
data.set_index(['Index1','Index2'],inplace=True,drop=True)
print(data)
 '''
                col1
Index1 Index2       
1      a         one
2      b         two
3      c       three
4      d         one
5      e         two
 '''
index_order=['Index2','Index1']  # Order of indexes we want
data= data.reorder_levels(index_order,0) # Reorder the indexes
print(data)
'''
                col1
Index2 Index1       
a      1         one
b      2         two
c      3       three
d      4         one
e      5         two
'''
# ------------------------------------------------------------

However, all azure pipeline tests failed. Can anyone tell me how can I resolve the issue?

**Comment by Josh-01** [comment]
Hi @Ashis26,
Is this issue still relevant for you ?

**Comment by tjcorr** [comment]
This repository only covers the GitHub Action: Azure/pipelines Other Azure DevOps questions can be raised via a support ticket or through the community hub: https://techcommunity.microsoft.com/t5/azure-devops/bd-p/AzureDevOpsForum
