### ISSUE TITLE
Git Action fails after connection creation 

### ISSUE THREAD

**Issue by talalalamdar-tomtom** [Azure/pipelines#52]
My Git Action workflow fails after connection is created with Azure DevOps service, getting `Error: Could not queue the build because there were validation errors or warnings.` as it shows in the screenshot below.

![Screenshot 2021-12-31 at 13 49 55](https://user-images.githubusercontent.com/93593445/147824321-4c525c80-dd67-4a47-98c8-90377486074c.png)

**Comment by Josh-01** [comment]
Hi @talalalamdar-tomtom , is this still an issue for you ?

**Comment by talalalamdar-tomtom** [comment]
Yeah it was, i had to change my implementation, by not using git action anymore and just use auto trigger from the azure pipeline it self

**Comment by cooper667** [comment]
Same issue here. No real way to see what is happening

**Comment by nnellanspdl** [comment]
Ran into this issue and was able to resolve it by making sure my Azure Pipeline had a default value set for all input parameters.  When being triggered by the GitHub Action, the Pipeline is forced to use default values for all input parameters.

**Comment by vijayma** [comment]
Since parameters cannot be passed in when invoked from this action, one would have to ensure that all the parameters are set in a different manner - aka defaults. Closing this issue.

**Comment by jessetan** [comment]
There is an open PR to be able to specify parameters: #63
