### ISSUE TITLE
[Question] How can I pass variables to the Azure Devops Pipeline

### ISSUE THREAD

**Issue by pmmluis** [Azure/pipelines#56]
Hi,

I'm using this action and I'm able to trigger the DevOps pipeline, but I can't seem to get the variables working.
Using it like so:

runs-on: ubuntu-20.04
steps:
 - name: DevOps release trigger
   if: github.event_name == 'push'
   uses: Azure/pipelines@v1
   with:
    azure-devops-project-url: 'https://dev.azure.com/orgnization/project'
    azure-pipeline-name: 'Pipeline' # name of the Azure pipeline to be triggered
    azure-devops-token: '${{ secrets.AZURE_DEVOPS_TOKEN }}'
    azure-pipeline-variables: '{"Branch": "testbranch", "App.Name": "apptest"}' # optional stringified json

I was expecting to pass the variables to the Azure DevOps pipeline, but nothing happens. The variable exists on the DevOps pipeline but isn't updated when the release happens.

**Comment by mychalhackman** [comment]
It looks like v1.2 has added support for the variables and the v1 tag is not pointed to latest. The docs currently are a bit misleading.
When running on v1 a warning is thrown for the unexpected input: 
```Unexpected input(s) 'azure-pipeline-variables', valid inputs are ['azure-devops-project-url', 'azure-pipeline-name', 'azure-devops-token']```

**Comment by pmmluis** [comment]
> It looks like v1.2 has added support for the variables and the v1 tag is not pointed to latest. The docs currently are a bit misleading. When running on v1 a warning is thrown for the unexpected input: `Unexpected input(s) 'azure-pipeline-variables', valid inputs are ['azure-devops-project-url', 'azure-pipeline-name', 'azure-devops-token']`

That solved it for me. Thanks for the help.

**Comment by saivamsibodavulaTR** [comment]
I am having trouble in passing variables from workflow to azure pipeline.
not getting values names.

Need Help on this
