### ISSUE TITLE
[Bug] PublishPipelineArtifact fails if artifact contains a symbolic link

### ISSUE THREAD

**Issue by atindall9041** [Azure/pipelines#59]
Hi, I'm seeing an error when trying to run the PublishPipelineArtifact task (version 0.141.0) on an artifact which contains a symlink.

Here's the error message:
```
##[error]Unable to load symbolic/hard linked file.  Check 'fsutil behavior query SymlinkEvaluation' to ensure proper behavior.
##[debug]Processed: ##vso[task.logissue type=error;]Unable to load symbolic/hard linked file.  Check 'fsutil behavior query SymlinkEvaluation' to ensure proper behavior.
##[debug]Processed: ##vso[task.complete result=Failed;]
##[debug]   at Microsoft.VisualStudio.Services.BlobStore.Common.PrecomputedHashesGenerator.GetFileBlobDescriptorAsync(String rootDirectory, Boolean chunkDedup, Boolean shouldPreserveSymbolicLink, Boolean shouldPreservePermissionValue, PageItem pageItem, CancellationToken cancellationToken)
```
I think this is a duplicate of https://developercommunity.visualstudio.com/t/PublishPipelineArtifact1----errorUn/1102572?space=21&q=symlink&viewtype=all, but that issue says the problem was fixed in agent version 2.160.0, and we're running agent version 2.202.0. We're using Linux agents.

Do you know if this issue can be fixed, or if there is a workaround?

Please let me know what additional diagnostic information you need.

Thanks!

**Comment by vijayma** [comment]
Since this issue is not related to the GitHub action for invoking Azure Pipelines, can you please file this issue in this repo? https://github.com/Microsoft/azure-pipelines-tasks

**Comment by atindall9041** [comment]
Thank @vijayma, done
