### ISSUE TITLE
[Bug] macOS-latest Xamarin builds fail

### ISSUE THREAD

**Issue by AaronBastian** [Azure/pipelines#86]
Starting today, 7-14-2023, our Xamarin iOS builds that are currently building on macOS-latest images have been failing with the following error.

/Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(283,5): error NETSDK1073: The FrameworkReference 'NETStandard.Library' was not recognized.

This started happening today without any really code changes on our end. We even tried to build older releases that are now also failing.

What do we need to do differently to get our pipelines unblocked?

**Comment by tjcorr** [comment]
This repository only covers the GitHub Action: Azure/pipelines Other Azure DevOps questions can be raised via a support ticket or through the community hub: https://techcommunity.microsoft.com/t5/azure-devops/bd-p/AzureDevOpsForum
